import { map } from "@trpc/server/observable";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import React from "react";

const BuildsPage: NextPage = () => {

    const builds = trpc.builds.getBuilds.useQuery()

  return (
    <>
      <Head>
        <title>Builds</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex gap-6 min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <h1>Builds</h1>

        <Link href="/">Home</Link>

        <table>
            <thead></thead>
            <tbody>
                {builds.data?.map((build) => (
                    <tr key={build.id}>
                        <td>{build.id}</td>
                        <td>{build.matchup}</td>
                        <td>{build.build}</td>
                    </tr>
                ))}
            </tbody>
        </table>

      </main>
    </>
  );
};

export default Home;
