import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

// Using API instead of the standard TRPC naming
import { api } from "../utils/api";
import React from "react";

const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex gap-6 min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <h1>Weclome to SC2 Build Order Manager</h1>

        <Link href="/submit-build">Submit a new Build</Link>
        <Link href="/builds">View Builds</Link>
      </main>
    </>
  );
};

export default Home;
